#ifndef CRIPTO_STEGANOGRAPHY_BMPADT_H
#define CRIPTO_STEGANOGRAPHY_BMPADT_H

#define DATA_OFFSET_OFFSET 0x000A
#define WIDTH_OFFSET 0x0012
#define HEIGHT_OFFSET 0x0016
#define BITS_PER_PIXEL_OFFSET 0x001C
#define HEADER_SIZE 54
#define NO_COMPRESION 0
#define MAX_NUMBER_OF_COLORS 0
#define ALL_COLORS_REQUIRED 0

#define BMPImage BMPImageStruct*

#endif //CRIPTO_STEGANOGRAPHY_BMPADT_H
